<?php

declare(strict_types=1);

namespace EvidencyMonitor\Notifiers;

/**
 * Email Notifier
 *
 * Sends email notifications with scan results
 */
class EmailNotifier implements NotifierInterface
{
    private string $to;
    private string $from;
    private array $config;

    public function __construct(string $to, string $from = 'noreply@localhost', array $config = [])
    {
        $this->to = $to;
        $this->from = $from;
        $this->config = $config;
    }

    public function getName(): string
    {
        return 'email';
    }

    public function send(array $results): bool
    {
        $status = $results['summary']['status'] ?? 'UNKNOWN';
        $date = date('Y-m-d');

        $subject = "EvidencyMonitor Report {$date} - {$status}";

        $body = $this->generateEmailBody($results);

        $headers = [
            'From: ' . $this->from,
            'Content-Type: text/plain; charset=UTF-8',
            'X-Priority: ' . ($status === 'ERRORS' ? '1' : '3'),
            'X-Mailer: EvidencyMonitor/1.0',
        ];

        return mail($this->to, $subject, $body, implode("\r\n", $headers));
    }

    private function generateEmailBody(array $results): string
    {
        $lines = [];
        $sep = str_repeat('=', 60);

        $lines[] = $sep;
        $lines[] = "EVIDENCY MONITOR - CODE VALIDATION REPORT";
        $lines[] = $sep;
        $lines[] = "";
        $lines[] = "Timestamp: {$results['timestamp']}";
        $lines[] = "Status:    {$results['summary']['status']}";
        $lines[] = "";

        // Summary table
        $lines[] = str_repeat('-', 60);
        $lines[] = sprintf("%-20s | %-8s | %-8s | %-8s",
            "Project", "Files", "Errors", "Warnings");
        $lines[] = str_repeat('-', 60);

        foreach ($results['projects'] ?? [] as $name => $project) {
            $lines[] = sprintf("%-20s | %-8d | %-8d | %-8d",
                substr($name, 0, 20),
                $project['files_scanned'],
                $project['errors'],
                $project['warnings']
            );
        }

        $lines[] = str_repeat('-', 60);
        $lines[] = "";

        // Totals
        $lines[] = "TOTALS:";
        $lines[] = "  Total files:    {$results['summary']['total_files']}";
        $lines[] = "  Total errors:   {$results['summary']['total_errors']}";
        $lines[] = "  Total warnings: {$results['summary']['total_warnings']}";
        $lines[] = "";

        // Critical issues summary
        $criticalIssues = $this->getCriticalIssues($results);
        if (!empty($criticalIssues)) {
            $lines[] = str_repeat('-', 60);
            $lines[] = "CRITICAL ISSUES REQUIRING ATTENTION:";
            $lines[] = str_repeat('-', 60);

            foreach ($criticalIssues as $issue) {
                $lines[] = "  [{$issue['project']}] {$issue['file']}";
                $lines[] = "    {$issue['message']}";
            }
            $lines[] = "";
        }

        $outputDir = $this->config['output_dir'] ?? 'reports';
        $lines[] = "Full reports available at: {$outputDir}";
        $lines[] = "";
        $lines[] = $sep;
        $lines[] = "Generated by EvidencyMonitor v1.0.0";
        $lines[] = "https://github.com/output4you/evidency-monitor";
        $lines[] = $sep;

        return implode("\n", $lines);
    }

    private function getCriticalIssues(array $results): array
    {
        $critical = [];

        foreach ($results['projects'] ?? [] as $name => $project) {
            // Syntax errors
            foreach ($project['scanner_results']['syntax']['issues'] ?? [] as $issue) {
                $critical[] = [
                    'project' => $name,
                    'file' => $issue['file'],
                    'message' => 'Syntax error: ' . $issue['message'],
                ];
            }

            // Critical security issues
            foreach ($project['scanner_results']['security']['issues'] ?? [] as $issue) {
                if (in_array($issue['severity'] ?? '', ['critical', 'high'])) {
                    $critical[] = [
                        'project' => $name,
                        'file' => $issue['file'] . ':' . ($issue['line'] ?? '?'),
                        'message' => "[{$issue['severity']}] {$issue['message']}",
                    ];
                }
            }

            // Vulnerabilities
            foreach ($project['scanner_results']['dependencies']['vulnerabilities'] ?? [] as $vuln) {
                $critical[] = [
                    'project' => $name,
                    'file' => $vuln['package'],
                    'message' => "Vulnerability: {$vuln['title']}",
                ];
            }
        }

        return array_slice($critical, 0, 20); // Limit to 20 issues in email
    }
}
